### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "rio",
  "email": "rio@example.com",
  "password_hash": "mypassword"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "rio@example.com",
  "password_hash": "mypassword"
}
